ClangBuiltLinux/continuous-integration

.gitignore, .gitmodules, README.md, driver.sh
At a certain point, Travis can no longer init submodules that aren't up
to date. Move the repo management into the script.
Fixes #8.
=> ci: Remove linux submodule

LICENSE
=> License: assign copyright to the ClangBuiltLinux authors

.gitignore, .travis.yml, debian-setup.sh, driver.sh
Unfortunately, as we add new architectures, we are going to need more up
to date binaries that Trusty cannot provide (see #16). Move our building
infrastructure to Docker, which gives us a deterministic, configurable
environment every time. The only forseeable downside is no cacheable
ccache directory so slower builds but we are getting to a point where
constant development is slowing down. I have kept ccache support in
driver.sh so that anyone who uses it locally can still take advantage of
it.
Initially, we'll start with the latest Debian stable but if we need to
move to the unstable version (sid) for more up to date packages, it's as
easy as changing 'debian' to 'debian:sid' in .travis.yml and adjusting
the LLVM/Clang apt repo in debian-setup.sh.
=> ci: Switch to Docker

driver.sh
* Show current commit (before applying out of tree patches)
* Show time to complete make commands
Also, add some spacing to group sets of commands.
Closes #26.
=> driver.sh: Add some extra information

.travis.yml, debian-setup.sh
I think this is more intuitive, it makes the 'docker run' command
shorter, and I can document exactly what each cofiguration change
does.
=> .travis.yml: Move ccache configuration into debian-setup.sh

.gitignore, .travis.yml, driver.sh
It's important to test linux-next as that's where all new development happens.
We don't need to build it every branch push and pull request because it is only updated daily so I only have it building with our daily cron.
I have verified it does work properly on my fork: https://travis-ci.com/nathanchance/continuous-integration/builds/90488778
=> ci: Support linux-next

.travis.yml
Nick suggested moving this build to cron only in #30 to speed up pull
request validation because at our free tier, we only have access to
three concurrent jobs.
=> .travis.yml: Demote arm64 ld.bfd build to cron only

debian-setup.sh
The logs are full of noise about packages being installed. This is
noise.
Printing the stats before and after makes it hard to tell the difference
without doing math.  It's clearer to zero stats before. Then the stats
after are just for this build.  We don't care about the cache stats pre
run.  Clearing the stats DOES NOT clear the cache itself or reset its
size.
https://ccache.samba.org/manual/latest.html#_options
=> debian-setup: quiet down setup, and zero stats

driver.sh
driver.sh:59:20: warning: Use spaces, not commas, to separate array elements. [SC2054]
driver.sh:60:30: warning: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it. [SC2191]
driver.sh:61:30: warning: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it. [SC2191]
Also, slip in an extra space to match the other qemu_cmdline
definitions.
=> driver: Fix a couple of shellcheck warnings

debian-setup.sh
The job failure at [1] appears to have been due to the libelf-dev package being missing. It is available in the sid repositories [2] so we can install it directly.
[1]: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/157821684#L576
[2]: https://packages.debian.org/sid/libelf-dev
=> debian-setup: Install libelf-dev

.travis.yml, driver.sh, usage.txt
this obviously conflicts with #39 , so will rebase on top.
@ajs1984 and I discussed today seeing what was broken in these branches in stable, and sending the relevant backports to @gregkh rather than landing them in Android common kernels, since they merge down from LTS anyways.
We should move these to cron jobs (post submit), but doing so now would make it so that these new targets aren't tested.  Once we get a run, I'll either make the cron, or comment them out (if they're super broken) with a patch on top of this PR.
=> add arm64 LTS targets

driver.sh
We expect all of the commands to succeed and we want the script to error
if that is not the case.
=> driver: Call 'set -e' globally

.travis.yml, patches/4.14/powerpc/series.patch, patches/4.14/ppc64le, patches/4.19/powerpc/series.patch, patches/4.19/ppc64le
These can't be pushed upstream just yet because the series that fixes the error in https://github.com/ClangBuiltLinux/linux/issues/259 isn't merged into mainline (it is sitting in linux-next currently) and the lib/raid6 change hasn't been accepted. Once those make their way into mainline, I will send these two series to stable so they can be dropped here but it doesn't hurt to get some early testing in :)
Presubmit results: https://travis-ci.com/nathanchance/continuous-integration/builds/92789308
=> patches: Support PowerPC on 4.14 and 4.19

.gitignore
[skip travis]
use `/` prefix to signal ignoring dirs only if they're top level to the
git repo.  Otherwise adding patches to these patch dirs shows no
difference to git (as all dirs with this name are ignored regardless of
depth) and requires `git add -f`.
See also: https://stackoverflow.com/questions/6168736/how-do-i-tell-git-to-ignore-a-specific-filename-only-in-the-repositorys-top-lev
=> .gitignore: mark dirs as toplevel

patches/4.14/powerpc/series.patch
looks like just this one landed upstream, so the series file fails to apply that patch again.
=> patches: drop single ppc patch that landed in 4.14.85

README.md
This doesn't do anything without submodules.
=> README: Remove '-j' flag on git clone

patches/4.19/x86_64/0001-DO-NOT-UPSTREAM-x86-Avoid-warnings-errors-due-to-lac.patch
This patch file was symlinked to the mainline one, which needed to be
updated in #97 to account for another mainline commit.
Fixes the following Travis fail: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/164238085
Presubmit run: https://travis-ci.com/nathanchance/continuous-integration/builds/94392813
=> patches: 4.19: x86_64: Fix patch application

patches/4.19/x86_64/0001-DO-NOT-UPSTREAM-x86-Avoid-warnings-errors-due-to-lac.patch
I forgot the 4.19 file was symlinked to the mainline file when I did
commit 81337479092e ("patches: linux: x86_64: Fix build on 5.0-rc1").
Fixes the following Travis fail: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/168809108
Presubmit run: https://travis-ci.com/nathanchance/continuous-integration/builds/96646483
=> patches: 4.19: x86_64: Fix application after 5.0 fixup

patches/linux/x86_64/x86-series.patch
The actual name of the option is CC_HAS_ASM_GOTO. It ultimately doesn't
matter now because we don't have asm goto support so this won't be
defined regardless but eventually, we will.
=> patches: linux: x86_64: Fix CONFIG name

patches/linux/x86_64/x86-series.patch
Guenter reports that with this patch, compilation fails:
$ make CC=clang-5.0 -j30
scripts/kconfig/conf --syncconfig Kconfig
arch/x86/Makefile:297: *** recipe commences before first target. Stop.
Move the KBUILD_CFLAGS assignment up where the reptoline flags are
passed along to mirror how those flags are handled to fix this.
=> patches: linux: x86_64: Fix passing of __BPF_TRACING__ to KBUILD_CFLAGS

driver.sh, usage.txt
We've tailored driver.sh around our Docker image with regards to the
binary versions that we check for. A user might not have the latest
versions of Clang or llvm-ar installed. Check for all three versions
offered by apt.llvm.org, falling back to the generic binary name if
those are not found.
Additionally, for llvm-ar, do a sanity check that the user has a version
of llvm-ar that can actually build the kernel (has support for the P
modifier). If they don't fall back to regular GNU ar and let them know.
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/103470578
=> driver: Improvements around binary locating

driver.sh
`llvm-ar` will have `svn` in its version by default (when
`LLVM_VERSION_SUFFIX` is not set to anything during cmake).
```
+ check_ar_version
+ llvm-ar --version
+ grep -q LLVM
++ llvm-ar --version
++ grep version
++ sed -e 's/.*LLVM version //g' -e 's/[[:blank:]]*$//' -e 's/\.//g'
+ [[ 900svn -lt 900 ]]
./driver.sh: line 195: [[: 900svn: value too great for base (error token is "900svn")
```
=> driver: Fix check_ar_version with LLVM source builds

.travis.yml
I will work to get these two patches upstreamed so they can be dropped but I will need to add some additional justification to patch 2/2 (maybe @agners has some insight there, as my guess is that it just isn't necessary but something tells me RMK might want something more than that).
Travis presubmit run: https://travis-ci.com/nathanchance/continuous-integration/builds/93235172
=> Support building the arm32 kernel with lld

.travis.yml
To allow us to easily see regressions in LLVM/Clang.
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/104655766
=> travis: Test mainline with stable LLVM/Clang

patches/linux/x86_64/x86-series.patch
It has been merged into mainline and causes our build to fail: https://git.kernel.org/linus/a9c640ac96e19b3966357ec9bb586edd2e1e74de
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/105679013
=> patches: linux/linux-next: x86_64: Drop headers patch

patches/4.14/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/4.19/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/4.4/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/4.9/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/common-4.14/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/common-4.19/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/common-4.9/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch
I wasn't paying attention in #146 and removed the patch that everything
was symlinked to...
4.4 will probably be the last release to get this patch due to the
timing of LTS releases so put the real patch there and symlink
everything to it.
=> patches: Fix application

driver.sh
qemu_ram only needs to be assigned to something different if the default
causes issues. Move the default assignment to its first use, which will
make adding new architectures this script easier as there is one less
variable to worry about.
=> driver: Use bash's default assignment operator for qemu_ram

driver.sh
This will help verify that LLD is working for linking.
```
+ readelf --string-dump=.comment vmlinux
String dump of section '.comment':
[     0]  clang version 9.0.0 (git://github.com/llvm/llvm-project c84107612ad7c73679996b6b0fb39a7423f0058d)
[    62]  Linker: LLD 9.0.0 (git://github.com/llvm/llvm-project c84107612ad7c73679996b6b0fb39a7423f0058d)
```
=> driver: Dump the comment section of vmlinux

patches/linux-next/x86_64/x86-series.patch
Commit e74deb11931f ("x86/uaccess: Introduce user_access_{save,restore}()")
in -next prevents the patch from applying cleanly, even with the three
way merge flag.
Link: https://git.kernel.org/tip/e74deb11931ff682b59d5b9d387f7115f689698e
Fixes: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/192907812
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/jobs/193055531
=> patches: linux-next: x86_64: Refresh

patches/4.14/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/4.19/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/4.9/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/common-4.14/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/common-4.19/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch, patches/common-4.9/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch
The patch has been released in 4.9.169, 4.14.112, and 4.19.35.
Fixes the following Travis fails: https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/108808195
=> patches: Remove bcmp patch for 4.9 to 4.19

.travis.yml, patches/4.4/x86_64/lld.patch
Addressing the following issues:
- ~https://github.com/ClangBuiltLinux/linux/issues/29~
- ~https://github.com/ClangBuiltLinux/linux/issues/218~
- ~https://github.com/ClangBuiltLinux/linux/issues/31~
- ~https://github.com/ClangBuiltLinux/linux/issues/94~
- ~https://github.com/ClangBuiltLinux/linux/issues/30~
=> Enabling LLD for x86_64

.travis.yml
This will never pass because LLD 8 does not support '-n'.
Failure: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/198494196
Cause: https://git.kernel.org/linus/691efbedc60d2a7364a90e38882fc762f06f52c4
=> travis: Remove arm64 lld build with LLVM 8

driver.sh
printing the version doesn't provide much meaningful info:
```
➜  kernel-all git:(master) ✗ llvm-nm --version
LLVM (http://llvm.org/):
LLVM version 9.0.0svn
Optimized build.
Default target: x86_64-unknown-linux-gnu
Host CPU: haswell
```
there's no version check because we don't have a minimum required version that we know about.
=> enable llvm-nm by default for all archs

.travis.yml
an lld target
Also, seems like `ARCH=arm32_v7 REPO=linux-next` was there twice.
The plan is to move to LLD; as targets can link with LLD we should spin
down the BFD builds, until we can just turn on LLD by default.
=> remove build targets for which don't use LLD for which there is already

driver.sh, usage.txt
This is now enabled by default on Cuttlefish 4.19, which causes issues
with our Debian setup because we do not have llvm-nm installed and it is
hardcoded that way in the Makefile:
https://github.com/aosp-mirror/kernel_common/blob/50f91435a27a9f7/Makefile#L617
It might be worth making that customizable in the future; however,
Travis cannot handle LTO for both time and memory reasons so just
disable it by default. A user can still pass '--lto' to driver.sh
to avoid disabling LTO (it will NOT attempt to enable it).
Fixes: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/202781149
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/113113278
=> driver: Disable LTO/CFI by default

.travis.yml
This has always been an LLVM 9 build since LLVM_VERSION wasn't being set... whoops.
=> travis: Fix x86_64 LLVM 8 build

driver.sh
This speeds up my local boots by 10s on average (24s to 14s).
We cannot unconditionally enable this because some machines (like the
ones on Travis CI) do not have KVM support, which would cause an error:
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize KVM: No such file or directory
https://travis-ci.com/nathanchance/continuous-integration/jobs/205427268
Check that the CPU supports virtualization from /proc/cpuinfo and that
the kvm module is enabled. As far as I can tell, every major
distribution sets CONFIG_KVM to m.
This is primarily aimed at local development (especially after #172) but
Travis may eventually gain virtualization support, which would speed up
CI.
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/buil …
=> driver.sh: Use KVM when possible

patches/llvm-8/linux/arm/0001-ARM-8860-1-VDSO-Drop-implicit-common-page-size-linke.patch
Conflicts occur because of
https://git.kernel.org/torvalds/c/c5d0e49e8d8f1a23034fdf8e935afc0c8f7ae27d.
Use the patch information and resolution from Russell King's tree:
http://git.armlinux.org.uk/cgit/linux-arm.git/commit/?id=b777a981d504678d7d90e7449a3da0b2924a2a76
http://git.armlinux.org.uk/cgit/linux-arm.git/commit/?id=60577ebf7718cf233bc67dc2a0c4089348da5c6b
Fixes builds 34 to 36: https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/116515113
=> patches: llvm-8: arm: Fix conflicts in common-page-size patch

usage.txt
`usage.txt` was not updated for a long time. This message was copied from `driver.sh` and coming back from 144150ce1111bf09726327b85ab9526d6d38cff8 and is not true anymore. Removed the misleading part.
=> LD variable is not used only with arm64 anymore

driver.sh
QEMU `-nographic` option is legacy and is kept only for compatibility. It does several things at once and not all of them are wanted. For example, it may clear screen when booting which is unwanted in most cases (but makes no difference with travis). Using `-display none -serial mon:stdio` ensures that the output is only added to the console.
=> Replace qemu -nographic option with better alternative

.travis.yml
All of the necessary patches have been applied to their respective trees
and they are all available in linux-next.
This requires a bump in the Docker image first: https://github.com/ClangBuiltLinux/dockerimage/pull/35
Presubmit will be run once that change has been merged.
=> travis: Enable 32-bit little endian MIPS on linux-next

.travis.yml
Now that all patches have been merged.
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/jobs/238347601
=> travis: Add MIPS 32-bit little endian to mainline targets

.travis.yml, driver.sh
android-4.9 branch was moved to remotes/origin/deprecated/android-4.9.
The branch android-4.9-q is the final branch. Android common kernel team
has recently changed their branching strategy.  It's recommended to
$ git fetch --prune
To see what branches are still alive.
=> rename android common branches that were moved.

.travis.yml
Local testing shows this works. Untested with lld-9, but we can always
undo that later.
arm32_v6 hits:
https://github.com/ClangBuiltLinux/linux/issues/732
=> link arm32_v5 with LLD

driver.sh
This build has been flaky since the 5.4 merge window it seems. I cannot
reproduce it locally so I believe it has something to do with Travis.
Increase the timeout to 4 minutes to make absolutely sure that the boot
has failed, rather than just being very long.
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/130365032
=> driver: Fix arm32_v6 flakiness

.travis.yml
Older stable is failing seemingly related to incremental linking being
removed in 4.17-rc1:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f49821ee32b76b1a356fab17316eb62430182ecf
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5e18f0290f2eccb0f64e87fbfca6395f11985b4b
=> link more arm64 stable with LLD

driver.sh, usage.txt
=> enable llvm-size by default for all arch's

patches/llvm-all/linux-next/ppc64/0001-powerpc-prom_init-Use-ffreestanding-to-avoid-a-refer.patch, patches/llvm-all/linux/ppc64/0001-powerpc-prom_init-Use-ffreestanding-to-avoid-a-refer.patch
Fixes:
* https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/245766675
* https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/245766684
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/132016071
=> patches: ppc64: Add -ffreestanding patch to avoid bcmp error

.travis.yml
Xenial is now the default. While we don't use anything in this
environment, it is still good to get a newer version of Docker and other
host utilities should we ever need them.
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/132017016
Link: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
=> travis: Use Xenial instead of Trusty

patches/llvm-all/linux-next/ppc64/0001-powerpc-prom_init-Use-ffreestanding-to-avoid-a-refer.patch
Commit 6266a4dadb1d ("powerpc/64s: Always disable branch profiling for
prom_init.o") in linux-next causes a conflict with the current patch.
This is based on v5, as noted with the updated link.
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/137130721
=> patches: ppc64: Fix application on linux-next

driver.sh
fixes the observed warning:
./driver.sh: line 255: [[: 1000git: value too great for base (error token is "1000git")
which is my fault because I switched LLVM 10 to use `git` for suffixes
rather than `svn` for non-release (ie. local dev) builds.
Link: https://github.com/llvm/llvm-project/commit/49fb4a96e0b79e18aec0ed908676ae4ecaf3084b
=> remove `git` suffixes from clang version as well

.travis.yml
Before this change travis config validation produces the following messages:
- `[WARN]` `root`: deprecated key `sudo` (The key `sudo` has no effect anymore.)
- `[INFO]` `root`: key `matrix` is an alias for `jobs`, using `jobs`
=> Update travis configuration to pass new build config validation without warnings

.travis.yml, driver.sh
Closes: #152 
Requires: https://github.com/ClangBuiltLinux/dockerimage/pull/40
=> S390 support

patches/llvm-11/4.4/arch-all/0001-scripts-dtc-Remove-redundant-YYLOC-global-declaratio.patch
`$ cp patches/llvm-11/4.9/arch-all/0001-scripts-dtc-Remove-redundant-YYLOC-global-declaratio.patch patches/llvm-11/4.4/arch-all/0001-scripts-dtc-Remove-redundant-YYLOC-global-declaratio.patch`
Fixes: #239
=> fix arm64 4.4 build

.travis.yml, driver.sh
As suggested in https://github.com/ClangBuiltLinux/continuous-integration/pull/70#issuecomment-599714608, RISC-V targets are only enabled on linux-next, so they would build fine without the patches. Build logs for these targets can be found [here](https://github.com/ClangBuiltLinux/continuous-integration/runs/512210549).
=> Build RISC-V target only for -next

driver.sh, usage.txt
This was useful back when arm64 was the only target we could reliably
build, but being explicit here is better and our .travis.yml already
passes an ARCH for all cases.
=> remove arm64 default

.travis.yml, build-all.sh, driver.sh
Debian symlinks their versioned binaries (clang-11, ld.lld-11, etc) in
/usr/bin from /usr/lib/llvm-#/bin. As a result, we do not need to
account for the suffixes, we can just add that folder to PATH if it
exists.
This simplies our CI matrix and handling within the script.
The CI failure in presubmit below is related to
https://github.com/ClangBuiltLinux/linux/issues/962, I just wanted to
show that the versioning detection still works properly afte this
patch.
Closes: https://github.com/ClangBuiltLinux/continuous-integration/issues/247
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/157635172
=> ci: Get rid of versioning binary scheme

.travis.yml
This works fine and avoids the error in the issue below.
Closes: https://github.com/ClangBuiltLinux/linux/issues/967
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/157639008
=> travis: Use integrated assembler for RISCV

driver.sh
except for s390, which does not appear to have any support for it in
the LLVM tools.
Tested locally with build-all.sh.
Closes: https://github.com/ClangBuiltLinux/continuous-integration/pull/212
Closes: https://github.com/ClangBuiltLinux/continuous-integration/issues/249
=> driver: Enable llvm-objcopy and llvm-strip

.travis.yml, driver.sh
By switching to `malta_kvm_guest_defconfig`, we can enable `ld.lld` now. See individual commit messages for reasoning.
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/158431604
=> Enable LLD for MIPS

.travis.yml, driver.sh, usage.txt
Fixes: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/317603327
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/159668906
=> driver/travis: Replace AS=clang with LLVM_IAS=1

.github/workflows/main.yml, build-all.sh, driver.sh
Uses [mvdan/sh](https://github.com/mvdan/sh) to enable formatting checks in CI, and correctly fails when the codestyle is [incorrect](https://github.com/msfjarvis/boot-utils/actions/runs/85612538), outputting a diff with fixes.
I chose the set of options that made the most sense to me, all available switches are listed [here](https://bin.msfjarvis.dev/~5ea167531de3ad00122e4ec0).
=> Reformat shell scripts with shfmt and validate in CI

driver.sh
There appears to be a bug in llvm-objcopy that was exposed by increasing
the page size to 64K for 32-bit ARM.
Move to GNU objcopy until that it fixed.
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/162491349
=> driver: Move to GNU objcopy for arm32_v5 for now

driver.sh
This reverts commit 4db0c1e19f8dc7ee6f9ae8ae50d20930ba689c39.
The issue has been fixed and the fix is available in the version of
LLVM that our Docker container uses:
https://github.com/llvm/llvm-project/commits/cc1c5165585/llvm/tools/llvm-objcopy
https://github.com/llvm/llvm-project/commit/ec786906f5feb4dceba1b5338927079e63e78095
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/163450700
=> Revert "driver: Move to GNU objcopy for arm32_v5 for now"

.travis.yml, patches/llvm-all/linux-next/x86/x86-boot-allow-a-relocatable-kernel-to-be-linked-with-lld.patch, patches/llvm-all/linux/x86/x86-boot-allow-a-relocatable-kernel-to-be-linked-with-lld.patch, usage.txt
https://github.com/ClangBuiltLinux/linux/issues/579
=> Enable LLD for i386

driver.sh
https://github.com/ClangBuiltLinux/continuous-integration/pull/253 added support for `objcopy` and `strip` utilities, but they couldn't be specified on the command line.
=> Allow objcopy and strip binaries to be specified

.travis.yml, patches/llvm-all/linux-next/arm64/silence-dwarf2-warnings.patch
As seen [here](https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/builds/164981592), arm32_v5, arm64, x86 and x86_64 already have all necessary patches on linux-next to be built with integrated-as enabled. ARM64 still produces a lot of warnings due to https://github.com/ClangBuiltLinux/linux/issues/716.
=> Enable integrated-as on selected arches on linux-next

.travis.yml
The series to fix https://github.com/ClangBuiltLinux/linux/issues/785
exposed an issue with ld.lld, which breaks the build.
Move this target to ld.bfd while we discuss how to fix it so that this
target is not blocked for testing.
Link: https://github.com/ClangBuiltLinux/linux/issues/1025
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/166566747
=> travis: Move MIPS big endian to ld.bfd on -next for now

.travis.yml
See commit 8cdfba2 ("travis: Move MIPS big endian to ld.bfd on -next
for now") for more reasoning.
=> travis: Move MIPS big endian to ld.bfd on mainline for now

.travis.yml
Our CI will be perpetually red with this enabled while the bug linked in
the comments is being solved. Unwinding the patches that introduced this
failure will be rather difficult as they came as part of a series with a
merge (from what I can tell) and maintaining that is not worth the
hassle.
While we're here, remove the linux cron comment; mainline does not have
any crons.
=> travis: Disable ppc32 for now

driver.sh
zImage has always been a hardlink to uImage but as of a refactoring in
5.8-rc1, that is no longer guaranteed to be the case. Explicitly build
the uImage so that we can always boot with QEMU.
Link: https://lore.kernel.org/linuxppc-dev/87bllidmk4.fsf@mpe.ellerman.id.au/
=> driver.sh: Build uImage for ppc32

driver.sh
Fixes: https://github.com/ClangBuiltLinux/linux/issues/1058
=> Increase aarch64 timeout from 2m to 3m

.travis.yml
Note, as of next-20200707, arm32 and arm64 boot is broken but should be
fixed in next-20200708 for reasons unrelated to LLVM:
https://lore.kernel.org/dmaengine/5f036d83.1c69fb81.10199.06d0@mx.google.com/
https://lore.kernel.org/dmaengine/159404871194.45151.3076873396834992441.stgit@djiang5-desk3.ch.intel.com/
No presubmit testing is done for that reason but this has been verified
locally.
Fixes: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/358277535
Link: https://github.com/ClangBuiltLinux/linux/issues/1078
=> travis: Disable the integrated assembler for arm64

.travis.yml, driver.sh
android-4.19 has been moved to deprecated/android-4.19, meaning it will
no longer see updates. android-4.19-stable should be the equivalent
(similar to android-4.14-stable):
https://android-review.googlesource.com/c/kernel/manifest/+/1359844
Fixes the following builds:
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/359204121
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/359204126
Additionally, android-5.4 has been shuffled to android12-5.4:
https://android-review.googlesource.com/c/kernel/manifest/+/1358083
https://android-review.googlesource.com/c/kernel/manifest/+/1358088
android-5.4 still technically exists but do not rely on that always
being true and just do that change now so that we do not have to do it
later when the build …
=> ci: Update certain Android branches for recent upstream changes

.travis.yml, patches/llvm-12/4.14/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/4.19/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/4.4/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/4.9/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/5.4/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/android-4.14-stable/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/android-4.19-stable/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/android-4.9-q/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/android-mainline/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/android12-5.4/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/linux-next/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch, patches/llvm-12/linux/arch-all/0001-Makefile-Fix-GCC_TOOLCHAIN_DIR-prefix-for-Clang-cros.patch
We need all of the patches because of
https://github.com/ClangBuiltLinux/linux/issues/1099.
Testing was done locally as this depends on the Docker image uprev:
https://github.com/ClangBuiltLinux/dockerimage/pull/53
=> travis: Upgrade to LLVM 11/12 from LLVM 10/11

driver.sh
The referenced issue https://github.com/ClangBuiltLinux/linux/issues/35
was fixed in 2019 when clang 10 gained support for this feature on arm.
Signed-off-by: Joel Stanley <joel@jms.id.au>
=> driver: Don't skip ftrace on arm32

.travis.yml
This reverts commit 590e48344c13e5910021b7cd1268dd93b8ab96b7.
This has been fixed: https://github.com/ClangBuiltLinux/linux/issues/1092
Unfortunately, the build will still be broken; still pending
investigation. I am only doing this so that I do not forget.
=> Revert "travis: Disable booting for RISC-V on linux-next for now"

.travis.yml, driver.sh, patches/llvm-all/linux-next/riscv/setup.c.patch
This pull "fixes" RISC-V builds and should make the build fully green.
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/181740252
The first two patches workaround https://github.com/ClangBuiltLinux/linux/issues/1143 and https://github.com/ClangBuiltLinux/linux/issues/1144. `BOOT=false` is necessary because the QEMU shipped in Ubuntu/Debian appears to be bugged as stock QEMU 4.2.0 and 5.0.0 work fine. We could probably start building QEMU in our Docker image but that is a significant amount of overhead and yet another binary that we have to triage issues with.
An alternative to this is just dropping RISC-V support for the time being until the architecture has matured a bit more. I do not personally care either way but we should really get the whole matrix …
=> RISC-V fixes

driver.sh
arm64 builds have recently been timing out during boot on mainline and
next, regardless of LLVM version. It is possible this is something that
should be investigated on the kernel side but local reproduction is a
bit more difficult due to higher power cores than what are available on
Travis. Just increase the timeout to 8m to be sure that we are hung.
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/183784691
=> driver: Increase timeout for arm64 to 8m

.travis.yml
Tested locally; we could probably go further but I only tested LLVM=1
for arm32_v7, arm64, and x86_64 back to 4.19.
Also, LLVM_IAS=1 works on mainline for arm32_v5.
=> expand LLVM=1 coverage

patches/llvm-all/linux/arm64/silence-dwarf2-warnings.patch
Apply 3466e54 ("patches: llvm-all: linux-next: Fix arm64 DWARF warning
patch") to the mainline patch for the same exact reason.
Fixes: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/407165664
Fixes: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/407165719
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/193051719
=> patches: llvm-all: linux: Fix arm64 DWARF warning patch

driver.sh
boot-utils master branch was renamed to main.
Signed-off-by: Sami Tolvanen <samitolvanen@google.com>
=> driver.sh: Update the branch for boot-utils
