- .travis.yml
- driver.sh
Probably will need to rebase once #18 lands.
> add lld to the testing matrix

- .travis.yml
- debian-setup.sh
These changes are in preparation for enabling ppc64le.
> Switch to Debian sid and Qemu 3.0

- .travis.yml
Move ccache from travis docker cmd to driver.
> travis: export REPO Fixes #41

- driver.sh
prefer:
if x:
...
else:
...
to:
if !x:
...
else:
...
> driver: small cleanup

- .travis.yml
4.19.2 with the LSE flag removal patch has been released.
https://travis-ci.com/nathanchance/continuous-integration/jobs/158304553
> travis: Enable 4.19 arm64

- driver.sh
As requested by @dileks on #110.
https://travis-ci.com/nathanchance/continuous-integration/builds/96501873#L533
> driver: Make git apply verbose

- .travis.yml
> travis: Maybe fix email notifications

- .travis.yml
- driver.sh
:) https://github.com/llvm/llvm-project/commit/1fe469ae6cd912248e4d754cc59c1231576a36eb
Depends on https://github.com/ClangBuiltLinux/dockerimage/pull/19
> CI: 's/-8/-9/g'

- .travis.yml
- driver.sh
- usage.txt
See the commit messages for the full details :)
> Add support for kernel/common

- driver.sh
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/103463243
> driver: Test booting arm64 kernels at both EL1 and EL2

- .travis.yml
The required CI change for https://github.com/ClangBuiltLinux/dockerimage/pull/20
> travis: Use our Debian image

- driver.sh
- patches/all/v4-0001-lib-string.c-implement-a-basic-bcmp.patch
This probably wont get used too often, as patches probably wont apply
cleanly across all these different branches, but makes it simple to
apply patches to many trees.
Also, add patch for
https://github.com/ClangBuiltLinux/linux/issues/416
> add facility to apply patches to all branches.

- .gitignore
I forgot to do this after turning on kernel/common builds
> gitignore: Add common folder

- build-all.sh
This is a script that will run all of the builds that Travis does on a
local user's machine. This can help validate changes faster than Travis
can if the user has a very fast machine (like I do).
> build-all.sh: Initial revision

- .travis.yml
Presubmit: https://travis-ci.com/nathanchance/continuous-integration/builds/132016315
> travis: Add MIPS little endian target for LLVM 9

- .travis.yml
- driver.sh
Also, this is the first LTS branch for mips.  We could add some ppc,
too.
> add 5.4, android-5.4, and android-mainline branches

- patches/llvm-all/kernel-all/Remove_redundant_YYLOC_global_declaration.patch
https://git.kernel.org/pub/scm/utils/dtc/dtc.git/commit/?id=0e9225eb0dfec51def612b928d2f1836b092bc7e
Reported-by: Nathan Chancellor <natechancellor@gmail.com>
> add dtc patch for yylloc

- .github/workflows/main.yml
To ensure that any contributions are consistent and proper, add a GitHub
Action that runs shellcheck on any scripts.
For an example of how an error manifests and gets reported:
https://github.com/nathanchance/boot-utils/actions/runs/68702038
> github: Add Actions workflow

- driver.sh
Tested locally with build-all.sh
> driver: Use llvm-readelf

- .travis.yml
Let's see if this works.
Closes: #257
> travis: Send failure emails for crons only

- .travis.yml
- driver.sh
Closes: https://github.com/ClangBuiltLinux/continuous-integration/issues/263
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/160088229
> driver/travis: android-4.14 is now android-4.14-stable

- .travis.yml
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/160086267
> travis: RISC-V can be built on mainline now

- .travis.yml
Depends on https://github.com/ClangBuiltLinux/dockerimage/pull/46.
> travis: Switch to Ubuntu Docker image

- usage.txt
Comments and corrections are welcome!
> Update the documentation to match what driver.sh actually does now

- .travis.yml
Link: https://github.com/ClangBuiltLinux/linux/issues/1043
> disable LLVM_IAS=1 for x86+x86_64 on -next

- .travis.yml
This reverts commit cfc8c91e31cedbaa0097ec3728a8b289ee5bace6.
https://github.com/ClangBuiltLinux/linux/issues/1044
https://reviews.llvm.org/D81767
> Revert "travis: Disable ppc32 for now"

- .travis.yml
- README.md
- driver.sh
https://github.com/ClangBuiltLinux/linux/issues/867
> Riscv boot

- .travis.yml
- driver.sh
Commits are fairly self explanatory.
Fixes the following fail: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/353017995
> Two RISC-V improvements

- .travis.yml
- driver.sh
These two commits along with #290 should make CI go green again.
> Two fixes for PowerPC and RISC-V failures

- patches/llvm-12/kernel-all/v2_20200811_nivedita_x86_boot_compressed_disable_relocation_relaxation.patch
> bring x86_64 back online, fixes boot failures

- .travis.yml
Closes: https://github.com/ClangBuiltLinux/continuous-integration/issues/309
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/182516369
> Enable the integrated assembler for x86 32-bit

- patches/llvm-12/android-mainline/x86_64/0001-x86-lib-Change-.weak-to-SYM_FUNC_START_WEAK-for-arch.patch
- patches/llvm-12/linux-next/arm32_v5/0001-ARM-Change-arch-arm-lib-mem-.S-to-use-WEAK-instead-o.patch
- patches/llvm-12/linux-next/riscv/so2s.sh.patch
- patches/llvm-12/linux-next/x86_64/0001-x86-lib-Change-.weak-to-SYM_FUNC_START_WEAK-for-arch.patch
- patches/llvm-12/linux/x86_64/0001-x86-lib-Change-.weak-to-SYM_FUNC_START_WEAK-for-arch.patch
All commits should be pretty self explanatory :)
Presubmit: https://travis-ci.com/github/nathanchance/continuous-integration/builds/198943639
> Fix all the red as of November 6, 2020
